version: "3.7"
services:
  code-server:
    image: codercom/code-server:4.16.1-ubuntu
    container_name: code-server
    environment:
      - PASSWORD=Password
    volumes:
      - ./config:/config
      - $PWD:/home/coder/workspace
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - code-server 
networks:
  code-server:      
    driver: bridge
